apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie 
  namespace: mealie 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie 
  template:
    metadata:
      labels:
        app: mealie 
    spec:
      securityContext:
        fsGroup: 911 # www-data group ID
        runAsUser: 911 # www-data user ID
        runAsGroup:  911 # www-data group ID
      containers:
        - name: mealie 
          image: ghcr.io/mealie-recipes/mealie:v3.20.1 
          ports:
            - containerPort: 9000

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: mealie-data 
              mountPath: /app/data

      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data-pvc
