apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
  namespace: n8n
  labels:
    app: n8n-db
spec:
  instances: 3
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-db-creds

  storage:
    size: 1Gi
