apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-store-n8n
  namespace: n8n
spec:
  provider:
    azurekv:
      tenantID: "f96fa795-2bcd-4282-b567-572483106349"
      vaultUrl: "https://kv-homelab-test.vault.azure.net"
      authSecretRef:
        clientId: 
          name: secrets-store-creds
          key: ClientID
        clientSecret:
          name: secrets-store-creds
          key: ClientSecret

