apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-tunnel-secrets
  namespace: linkding
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  provider: azure

  parameters:
    keyvaultName: kv-homelab-test

    objects: |
      array:
        - |
          objectName: cloudflare-tunnel-creds
          objectType: secret
          objectAlias: credentials.json
    tenantID: "f96fa795-2bcd-4282-b567-572483106349"
  nodePublishSecretRef:
    name: secrets-store-creds
