apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-n8n-tunnel-secrets
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-store-n8n
    kind: SecretStore
  target:
    name: n8n-tunnel-creds
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: n8n-tunnel-creds
