apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-n8n-tunnel-secrets
  namespace: n8n 
spec:
  provider: azure

  parameters:
    keyvaultName: kv-homelab-test

    objects: |
      array:
        - |
          objectName: n8n-tunnel-creds
          objectType: secret
          objectAlias: credentials.json
#       - |
#         objectName: n8n-db-username
#         objectType: secret
#       - |
#         objectName: n8n-db-password
#         objectType: secret

    tenantID: "f96fa795-2bcd-4282-b567-572483106349"

  secretObjects:
#   - secretName: n8n-creds
#     type: Opaque
#     data:
#       - objectName: n8n-db-username
#         key: DB_POSTGRESDB_USER
#       - objectName: n8n-db-password
#         key: DB_POSTGRESDB_PASSWORD

    - secretName: n8n-db-creds
      type: kubernetes.io/basic-auth
      data:
        - objectName: n8n-db-username
          key: username
        - objectName: n8n-db-password
          key: password

