apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: monitoring 
spec:
  provider: azure

  parameters:
    keyvaultName: kv-homelab-test

    objects: |
      array:
        - |
          objectName: grafan-username
          objectType: secret
        - |
          objectName: grafana-user-password
          objectType: secret
    tenantID: "f96fa795-2bcd-4282-b567-572483106349"
    
  secretObjects:                                 
    - secretName: grafana-creds
      type: Opaque
      data:
        - objectName: grafana-username                   
          key: GF_SECURITY_ADMIN_USER 
        - objectName: grafana-user-password
          key: GF_SECURITY_ADMIN_PASSWORD
