apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: linkding
spec:
  provider: azure

  parameters:
    keyvaultName: kv-homelab-test

    objects: |
      array:
        - |
          objectName: linkding-username
          objectType: secret
        - |
          objectName: linkding-user-password
          objectType: secret

  secretObjects:                                 
    - secretName: linkding-creds
      type: Opaque
      data:
        - objectName: linkding-username                   
          key: LD_SUPERUSER_NAME
        - objectName: linkding-user-password
          key: LD_SUPERUSER_PASSWORD

    tenantID: "f96fa795-2bcd-4282-b567-572483106349"
  nodePublishSecretRef:
    name: secrets-store-creds



